#!/usr/bin/env bash

set -Eeuo pipefail

if [ -z "${BASH_SOURCE[0]:-}" ]; then
  # zsh
  LIBEXEC_DIR="${0:A:h}"
else
  LIBEXEC_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
fi

ROOT_DIR="$(dirname "${LIBEXEC_DIR}")"

TMP_DIR="${ROOT_DIR}/tmp"

VCS="${1:-gitlab}"

cp "${ROOT_DIR}/.tool-versions" "${ROOT_DIR}/tests/"

docker image build --rm --no-cache -t gcmpb-build "${ROOT_DIR}/tests/"

docker volume create gcmpb-asdf

docker run -ti \
  --env VCS="${VCS}" \
  --env GCMPB_GL_FILE_TOKEN="/root/git-cleanup-merged-pr-branches/tmp/GCMPB_GL_FILE_TOKEN" \
  --env GCMPB_GH_FILE_TOKEN="/root/git-cleanup-merged-pr-branches/tmp/GCMPB_GH_FILE_TOKEN" \
  --env GITHUB_DEPLOY_KEY="/root/git-cleanup-merged-pr-branches/tmp/GITHUB_DEPLOY_KEY" \
  --env AZURE_DEVOPS_EXT_PAT="$(cat "${TMP_DIR}/AZURE_DEVOPS_EXT_PAT")" \
  --mount source=gcmpb-asdf,target=/root/.asdf \
  -v "${ROOT_DIR}":/root/git-cleanup-merged-pr-branches \
  -w /root/git-cleanup-merged-pr-branches \
  gcmpb-build \
  /root/git-cleanup-merged-pr-branches/tests/local-docker-bootstrap.sh
